auto: true
server: true
pygments: true
permalink: none
root_dir: ""
oauth_client_id: caf55c20366465a1332d
gatekeeper_url: http://poole-oauth-staging.herokuapp.com
exclude:
- .gitignore
- README.md
prose:
  rooturl: '_posts'
  siteurl: 'http://www.example.com/'
  media: 'assets/blog'
  ignore:
    - index.html
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "category"
        field:
          element: "select"
          label: "Kategorie"
          placeholder: "Wählen Sie eine Kategorie aus"
          options:
            - name: "Kategorie1"
              value: "kategorie1"
            - name: "Kategorie2"
              value: "kategorie2"